### ISSUE TITLE
Widget: Columns design

### ISSUE THREAD

**Issue by DandyReyes** [electrala/documentation#39]
Make another widget on top of the plus sign widget so the user can decide how many images per column they want to see.

**Comment by brennannewton** [comment]
What do you mean by, "...the user can decide how many images per column they want to see?"

**Comment by DandyReyes** [comment]
Good Question. Sorry for the vagueness. It means that the user can decide how many images they prefer to see per row. For instance, if someone rather see less images per row, say 3 instead of 6, then there is that option available for them.
